### ISSUE TITLE
A string with no rule throws an AttributeError

### ISSUE THREAD

**Issue by Kylearan** [plyara/plyara#10]
A string which consists only of imports and/or comments but no rule definitions (which is not uncommon for large collections organized in multiple files) throws ```AttributeError: 'NoneType' object has no attribute 'type'```.

**Comment by rshipp** [comment]
Good catch, thanks for the issue.

**Comment by rshipp** [comment]
I've pushed a new release that should fix this ([v1.2.1](https://github.com/plyara/plyara/releases/tag/v1.2.1)). Let me know if you have any more issues.
