### ISSUE TITLE
Looking for New Maintainer

### ISSUE THREAD

**Issue by utkonos** [plyara/plyara#119]
I no longer have the resources to devote to maintaining plyara. If there is another maintainer or maintainers who would like to step forward and continue maintaining this project, please reply here.

**Comment by larsborn** [comment]
Hey,
I contributed to this project a few years ago: https://github.com/larsborn/plyara/commit/d0593170461cd9276fbe2b4253c64c2c7c005912 

I am using it quite regularly and would hence have the motivation and would need to carve out the time to carry on. How would we go about this? How limited is your time? Would you, for example, have the time to accept contributions or is even that out of scope right now?

**Comment by utkonos** [comment]
Let me know if you're still interested. I'm back, and there are some Canadian Centre for Cyber Security people using the project as well that I'll be contacting to add as maintainers as well.

**Comment by larsborn** [comment]
Yep, still interested :-)

**Comment by utkonos** [comment]
I've sent you an invite. And I enabled discussions on the repo. We can continue coordination here:

https://github.com/orgs/plyara/discussions/140
