### ISSUE TITLE
Return Clean Python Types in Meta

### ISSUE THREAD

**Issue by utkonos** [plyara/plyara#12]
According to YARA spec, the meta section can contain strings, integers, and booleans. At the moment, playara returns everything as strings. Changing the type of an output is definitely a non-backwards compatible change, so we should add this to a 2.0.0 milestone.

Here are the details from the documentation: https://yara.readthedocs.io/en/v3.7.0/writingrules.html#metadata

**Comment by rshipp** [comment]
Agreed. We should remove any other double quoted output at the same time. Currently input like this

    $a = "string"

Results in output like this

    'strings': [{'name': '$a', 'value': '"string"'}]}]

Where the value includes the quotes. Makes using this output harder as we have to manually strip the quotes off, handle escaped quotes (`$a = "string\""`), etc.

**Comment by utkonos** [comment]
Good idea. I don't remember if I had fixed that in my fork. I need to check. Either way, both are breaking changes, so we can put them in a 2.0. I adjusted the name of this enhancement so it encompases both changes. No need for a separate ticket.
