### ISSUE TITLE
STRING_ESCAPE_CHARS should contain 'r'

### ISSUE THREAD

**Issue by immanuelAtTQ** [plyara/plyara#123]
see https://yara.readthedocs.io/en/stable/writingrules.html#text-strings

'r' is missing from STRING_ESCAPE_CHARS

**Comment by immanuelAtTQ** [comment]
I was able to fix this in my implementation by doing the following:

```            parser = Plyara()
    # Ensure '\r' is supported: https://yara.readthedocs.io/en/stable/writingrules.html#text-strings
    parser.STRING_ESCAPE_CHARS.add('r')  # HACK adds to predefined {'"', '\\', 't', 'n', 'x'}
    parsed_rules = `parser.parse_string(value)```

**Comment by Derekt2** [comment]
Also saw this issue, and confirmed your workaround worked!

**Comment by neiltyagi** [comment]
Yes due to this issue plyara throws error when parsing a rule where string part contains \r.


Kindly fix it
