### ISSUE TITLE
Turn off logging

### ISSUE THREAD

**Issue by evolution536** [plyara/plyara#129]
This library works like a charm, I love it. However, the amount of logging is enormous and INFO logging can't seem to be turned off. Is there a way this can be turned off with an option?

`
    INFO:plyara.core:Matched strings kvs
    INFO:plyara.core:Matched rule body
    INFO:plyara.core:Matched rule: win_cycbot_auto
    INFO:plyara.core:Matched meta kvs
    INFO:plyara.core:Matched meta kvs
`

I have already set console_logging to False but this does not seem to influence the behavior.

Thanks in advance!

**Comment by evolution536** [comment]
I see this pull request fixes my problems too: https://github.com/plyara/plyara/pull/126. Please merge this PR. :)

**Comment by utkonos** [comment]
@evolution536 Merged and thanks! Sorry for the long delay. I'll cut a new version after the weekend. I'm working on unit test cleanup before that.
