### ISSUE TITLE
detect_dependencies() misses references in parantheses

### ISSUE THREAD

**Issue by Kylearan** [plyara/plyara#13]
If a rule has a dependency in its condition section which is in parantheses, it will be missed by detect_dependencies().

Example:
```
rule a {
    condition:
    true
}

rule b {
    condition:
    (a) and true
}
```

detect_dependendies() will not detect that rule b references rule a. Remove the parantheses around a in b's condition section and it works.
Some open source yara repositories have rules with dependencies in parantheses.

**Comment by rshipp** [comment]
Interesting, I didn't know you could do this. I'll put together some test cases and see if I can get it working. Thanks for the issue!

**Comment by Kylearan** [comment]
A real-world example would be the rule "MALW_TinyShell_backconnect_Gen"
here:

https://github.com/Yara-Rules/rules/blob/master/malware/MALW_TinyShell_Backdoor_gen.yar


Am 25.07.2018 um 17:14 schrieb Ryan Shipp:

**Comment by rshipp** [comment]
Just pushed a new release ([v1.2.2](https://github.com/plyara/plyara/releases/tag/v1.2.2)) with @Taskr's fix for this bug. Thanks again for reporting, and feel free to reopen this issue if you find an edge case my tests didn't cover.
