### ISSUE TITLE
Error excluding comments in condition lines

### ISSUE THREAD

**Issue by Neo23x0** [plyara/plyara#24]
I noticed that a comment in a condition will be parsed as if it were part of the condition and appears in the `condition_terms`
```
rule EXE_extension_cloaking {
   meta:
      description = "Executable showing different extension (Windows default 'hide known extension')"
      author = "Florian Roth"
   condition:
      filename matches /\.txt\.exe$/is or   // Special file extensions
      filename matches /\.pdf\.exe$/is   // Special file extensions
}
```

```
>>> rule["condition_terms"]
['filename', 'matches', '/\\.txt\\.exe$/is or   //', 'Special', 'file', 'extensions', 'filename', 'matches', '/\\.pdf\\.exe$/is']
```

**Comment by Taskr** [comment]
Thanks for submitting this issue @Neo23x0. I was able to reproduce this behavior in v1.2.5 but appears to no longer be an issue in v1.2.6. I went ahead and submitted a pull request for review in response to the Regex string issue you submitted earlier.
