### ISSUE TITLE
Support for match length operator "!"

### ISSUE THREAD

**Issue by MrHigashi** [plyara/plyara#32]
Can we add support for the match length operator "!"? 

Here is the reference in the yara docs https://yara.readthedocs.io/en/v3.8.1/writingrules.html#match-length

**Comment by rshipp** [comment]
Thanks for the issue! I've pushed @utkonos's fix to PyPI as v1.3.3. Feel free to let us know if you find anything else.

**Comment by MrHigashi** [comment]
Will do and thanks. This has been very helpful
