### ISSUE TITLE
ParseValueError's t.lexer.lineno ignores bytestring new lines

### ISSUE THREAD

**Issue by ricardo-dias** [plyara/plyara#35]
The following rule:
```
rule sample
{
    strings:
        $ = { 00 00 00 00 00 00  
              00 00 00 00 00 00 } //line 5
    conditio: //fault
        all of them
}
```
Throws:
`Unknown text conditio for token of type ID on line 5`

Ideally it should consider the bytestring new line and return the exception at **line 6**.

Thanks in advance.
RD

**Comment by rshipp** [comment]
Thanks for the issue, I can see how this would become a problem. I've opened a PR to fix, and will tag a release once someone has had a chance to review it.

**Comment by ricardo-dias** [comment]
Thanks!
