### ISSUE TITLE
Offset char @ throw a ParseTypeError 

### ISSUE THREAD

**Issue by ricardo-dias** [plyara/plyara#37]
Rule:
```
rule sample
{
    strings:
        $ = { 01 02 03 04 }
    condition:
        for all of ($) : ( @ < 0xFF )
}
```
Throws:
```
plyara.ParseTypeError: Illegal character @ at line 6
```
Thanks in advance!
RD

**Comment by utkonos** [comment]
This PR fixes the issue. It's waiting on approval, but if you need to use plyara immediately you can use the PR branch here:

https://github.com/plyara/plyara/tree/issue37
