### ISSUE TITLE
Tag indicator specified but no tags causes exception

### ISSUE THREAD

**Issue by tlansec** [plyara/plyara#65]
Hello!

When parsing a rule like this plyara throws an exception on parsing the tags, and although odd this is a valid rule:

```
rule tmp : 
{
condition:
   false
}
```

Cheers,
Tom

**Comment by utkonos** [comment]
Thanks for the report. Will be fixing this.

**Comment by tlansec** [comment]
Actually - looks like i was wrong - not sure how i managed to mess up my test, but yara does indeed complain about the rule above. 

No longer as clearcut as to whether plyara should throw exception or not. It probably should.

**Comment by utkonos** [comment]
This rule does not appear to be a valid YARA rule. Here is the output:

```
$ yara test.yara test
test.yara(2): error: syntax error, unexpected '{', expecting identifier
```

I don't think the keyword "false" is allowed as a condition on its own. I'm going to close this issue.
