### ISSUE TITLE
Add New PLY as Vendor Directory

### ISSUE THREAD

**Issue by utkonos** [plyara/plyara#85]
PLY is no longer distributed as a package. There are a few options:

1. Add a vendor directory with the contents of PLY master and build it along with plyara.
2. Build and host a pypi installable PLY based on PLY master.
3. Do nothing and update to SLY.

https://github.com/dabeaz/ply/commits/master

**Comment by rshipp** [comment]
Looks like it's still there, are they just not pushing new versions? Either way, I'm fine with switching to SLY; it's 2020, py2 is officially dead.

**Comment by utkonos** [comment]
Sounds like a plan. I'm going to close this one. We have a SLY update issue already. I'll take some time soon and do the lift to SLY.
